# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MEkCGDRyvX7hp5EfcowxOqlWUu8S3IBK

# Import Library & Data
"""

import pandas as pd
import numpy as np
from pathlib import Path

file_path = "C:/Users/Khaira Salsabila/Downloads/Dashboard baru.xlsx"

df = pd.read_excel(
    file_path,
    sheet_name="Activity"
)

print("Jumlah baris:", len(df))
print("Jumlah kolom:", len(df.columns))

df.head()

"""# Data Eksplorasi"""

df.info()

df.columns.tolist()

"""# Rename Kolom""" 

df = df.rename(columns={
    "SSR": "ssr",
    "Bulan": "bulan",
    "BL": "bl",
    "jml kegiatan P (Planning)": "jml_kegiatan_planning",
    "Unit Cost": "unit_cost",
    "Total Budget": "total_budget",
    "Kab/kota2": "kab_kota",
    "Junlah Kegiatan yang R (Terealisasi)": "jml_kegiatan_realisasi",
    "Budget": "realisasi",
    "% Budget/Total Budget": "persentase_budget",
    "justifikasi": "justifikasi",
    "kategori BL ": "kategori_bl"
})

df.columns.tolist()

"""# Menghapus Missing Value Untuk Semua Baris"""

# MENGHAPUS MISSING VALUE

df = df.dropna(how="all").copy()

print("Jumlah baris setelah menghapus baris kosong:", len(df))

"""# Treatment Kolom Teks"""

text_columns = [
    "ssr",
    "bulan",
    "kab_kota",
    "justifikasi",
    "kategori_bl"
]

for col in text_columns:
    df[col] = (
        df[col]
        .astype("string")
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

df[text_columns] = df[text_columns].replace(
    {
        "": pd.NA,
        "-": pd.NA,
        "–": pd.NA,
        "—": pd.NA,
        "nan": pd.NA,
        "None": pd.NA
    }
)

"""# Treatment Kolom Numeric"""

numeric_columns = [
    "bl",
    "jml_kegiatan_planning",
    "unit_cost",
    "total_budget",
    "jml_kegiatan_realisasi",
    "realisasi",
    "persentase_budget"
]

# MEMPERBAIKI PENULISAN ANGKA PADA KOLOM NUMERIK

def clean_number(value):

    if pd.isna(value):
        return np.nan

    if isinstance(value, (int, float, np.integer, np.floating)):
        return float(value)

    value = str(value).strip()

    if value in ["", "-", "–", "—", "nan", "None"]:
        return np.nan

    value = value.replace("%", "")
    value = value.replace(" ", "")

    # Contoh:
    # 1.234.567,89 -> 1234567.89
    if "," in value and "." in value:

        if value.rfind(",") > value.rfind("."):
            value = value.replace(".", "")
            value = value.replace(",", ".")
        else:
            value = value.replace(",", "")

    # Contoh:
    # 1,234,567
    # atau
    # 123,45
    elif "," in value:

        parts = value.split(",")

        if len(parts[-1]) <= 2:
            value = value.replace(",", ".")
        else:
            value = value.replace(",", "")

    # Contoh:
    # 1.234.567
    elif value.count(".") > 1:
        value = value.replace(".", "")

    try:
        return float(value)

    except:
        return np.nan

for col in numeric_columns:
    df[col] = df[col].apply(clean_number)

df[numeric_columns].dtypes

"""# Memperbaiki Kolom "Bulan"
"""

month_map = {
    "jan": 1,
    "januari": 1,

    "feb": 2,
    "februari": 2,

    "mar": 3,
    "maret": 3,

    "apr": 4,
    "april": 4,

    "mei": 5,
    "may": 5,

    "jun": 6,
    "juni": 6,

    "jul": 7,
    "juli": 7,

    "agu": 8,
    "ags": 8,
    "aug": 8,
    "agustus": 8,

    "sep": 9,
    "sept": 9,
    "september": 9,

    "okt": 10,
    "oct": 10,
    "oktober": 10,

    "nov": 11,
    "november": 11,

    "des": 12,
    "dec": 12,
    "desember": 12
}

def get_month_number(value):

    if pd.isna(value):
        return np.nan

    value = str(value).strip().lower()

    # Hilangkan titik
    value = value.replace(".", " ")

    # Rapikan spasi
    value = " ".join(value.split())

    for key, number in month_map.items():

        if key in value:
            return number

    return np.nan

df["bulan_no"] = df["bulan"].apply(get_month_number)

df[["bulan", "bulan_no"]].drop_duplicates().sort_values("bulan_no")

month_names = {
    1: "Januari",
    2: "Februari",
    3: "Maret",
    4: "April",
    5: "Mei",
    6: "Juni",
    7: "Juli",
    8: "Agustus",
    9: "September",
    10: "Oktober",
    11: "November",
    12: "Desember"
}

df["bulan"] = df["bulan_no"].map(month_names)

df["tahun"] = 2026

df["tanggal_bulan"] = pd.to_datetime(
    {
        "year": df["tahun"],
        "month": df["bulan_no"],
        "day": 1
    },
    errors="coerce"
)

df["periode"] = df["tanggal_bulan"].dt.strftime("%Y-%m")

#APAKAH ADA BULAN YANG GAGAL DIBACA?

print(
    df[df["bulan_no"].isna()][["bulan"]]
)

print(df["bulan"].value_counts())

df.head()

"""# Isi Nilai Numerik dengan Angka 0"""

zero_columns = [
    "bl",
    "jml_kegiatan_planning",
    "unit_cost",
    "total_budget",
    "jml_kegiatan_realisasi",
    "realisasi"
]

for col in zero_columns:
    df[col] = df[col].fillna(0)

df.head()

"""# Validasi TOTAL BUDGET"""

df["total_budget_valid"] = (
    df["jml_kegiatan_planning"] *
    df["unit_cost"]
)

df["selisih_budget"] = (
    df["total_budget"] -
    df["total_budget_valid"]
)

df[
    df["selisih_budget"].abs() > 1
][
    [
        "bl",
        "jml_kegiatan_planning",
        "unit_cost",
        "total_budget",
        "total_budget_valid",
        "selisih_budget"
    ]
].head(20)

"""# Hitung Ulang Persentase Serapan"""

df["persentase_valid"] = np.where(
    df["total_budget_valid"] > 0,
    df["realisasi"] / df["total_budget_valid"],
    0
)

"""# Buat Flag Untuk Data yang Perlu Dicek"""

df["flag_realisasi"] = np.select(

    [
        df["realisasi"] < 0,

        df["realisasi"] > df["total_budget_valid"],

        df["realisasi"] == df["total_budget_valid"]
    ],

    [
        "Realisasi negatif",

        "Realisasi > Budget",

        "Realisasi = Budget"
    ],

    default="Normal"
)

df["flag_realisasi"].value_counts()

df[
    df["flag_realisasi"] != "Normal"
][
    [
        "ssr",
        "bulan",
        "bl",
        "total_budget",
        "realisasi",
        "persentase_valid",
        "flag_realisasi"
    ]
].head(20)

"""# Cek Duplicate"""

duplicate = df[df.duplicated(keep=False)]

print("Jumlah duplicate:", len(duplicate))

"""# Sorting Data"""

df = df.sort_values(
    [
        "tahun",
        "bulan_no",
        "ssr",
        "bl"
    ]
).reset_index(drop=True)

"""# Cek Hasil Akhir"""

print("Jumlah baris:", len(df))
print("Jumlah kolom:", len(df.columns))

df.info()

df[
    [
        "bulan",
        "bulan_no",
        "tahun",
        "tanggal_bulan",
        "periode"
    ]
].drop_duplicates().sort_values("bulan_no")

"""# Hanya Ambil Januari - Juni"""

# Hanya ambil data Januari sampai Juni 2026
df = df[df["bulan_no"].between(1, 6)].copy()

# Reset index
df = df.reset_index(drop=True)

print("Data setelah Juli–Desember di-drop:")
print(df["bulan"].value_counts().sort_index())

"""# Export ke Excel"""

output_file = "Dashboard baru_Cleaned.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    df.to_excel(
        writer,
        sheet_name="Activity_Clean",
        index=False
    )

